---
abstract: 'Mason wrapper for Dancer2'
author:
  - 'Yanick Champoux <yanick@cpan.org>'
build_requires:
  Dancer2::FileUtils: '0'
  ExtUtils::MakeMaker: '0'
  File::Spec: '0'
  IO::Handle: '0'
  IPC::Open3: '0'
  Test2::V0: '0'
  Test::More: '0'
  perl: '5.006'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: 'Dist::Zilla version 6.030, CPAN::Meta::Converter version 2.150010'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Dancer2-Template-Mason
no_index:
  directory:
    - inc
provides:
  Dancer2::Template::Mason:
    file: lib/Dancer2/Template/Mason.pm
    version: v0.1.2
requires:
  Dancer2::Core::Role::Template: '0'
  FindBin: '0'
  HTML::Mason::Interp: '0'
  Moo: '0'
  strict: '0'
  warnings: '0'
resources:
  bugtracker: https://github.com/yanick/Dancer2-Template-Mason/issues
  homepage: https://github.com/yanick/Dancer2-Template-Mason
  repository: https://github.com/yanick/Dancer2-Template-Mason.git
version: 0.1.2
x_author_pledge:
  version: 1
x_authority: cpan:YANICK
x_contributor_covenant:
  version: 0.02
x_contributors:
  - 'Jason A. Crome <jason@crome-plated.com>'
  - 'Yanick Champoux <yanick@babyl.ca>'
x_generated_by_perl: v5.38.0
x_serialization_backend: 'YAML::Tiny version 1.74'
x_spdx_expression: 'Artistic-1.0-Perl OR GPL-1.0-or-later'
